set_property PACKAGE_PIN L16 [get_ports clk_a]
set_property IOSTANDARD LVCMOS33 [get_ports clk_a]
create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports clk]

set_property PACKAGE_PIN G15 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

connect_debug_port u_ila_0/clk [get_nets [list clk_a_IBUF_BUFG]]
connect_debug_port dbg_hub/clk [get_nets clk_a_IBUF_BUFG]

set_property PACKAGE_PIN L16 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

connect_debug_port u_ila_0/probe0 [get_nets [list {u_bus2/u_slave1/rdata_o[0]} {u_bus2/u_slave1/rdata_o[1]} {u_bus2/u_slave1/rdata_o[2]} {u_bus2/u_slave1/rdata_o[3]} {u_bus2/u_slave1/rdata_o[4]} {u_bus2/u_slave1/rdata_o[5]} {u_bus2/u_slave1/rdata_o[6]} {u_bus2/u_slave1/rdata_o[7]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_bus2/u_slave1/wdata_i[0]} {u_bus2/u_slave1/wdata_i[1]} {u_bus2/u_slave1/wdata_i[2]} {u_bus2/u_slave1/wdata_i[3]} {u_bus2/u_slave1/wdata_i[4]} {u_bus2/u_slave1/wdata_i[5]} {u_bus2/u_slave1/wdata_i[6]} {u_bus2/u_slave1/wdata_i[7]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_bus2/u_master0/wdata_o[0]} {u_bus2/u_master0/wdata_o[1]} {u_bus2/u_master0/wdata_o[2]} {u_bus2/u_master0/wdata_o[3]} {u_bus2/u_master0/wdata_o[4]} {u_bus2/u_master0/wdata_o[5]} {u_bus2/u_master0/wdata_o[6]} {u_bus2/u_master0/wdata_o[7]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_bus2/u_slave1/addr_i[0]} {u_bus2/u_slave1/addr_i[1]} {u_bus2/u_slave1/addr_i[2]} {u_bus2/u_slave1/addr_i[3]} {u_bus2/u_slave1/addr_i[4]} {u_bus2/u_slave1/addr_i[5]} {u_bus2/u_slave1/addr_i[6]} {u_bus2/u_slave1/addr_i[7]} {u_bus2/u_slave1/addr_i[8]} {u_bus2/u_slave1/addr_i[9]} {u_bus2/u_slave1/addr_i[10]} {u_bus2/u_slave1/addr_i[11]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_bus2/u_master0/addr_o[0]} {u_bus2/u_master0/addr_o[1]} {u_bus2/u_master0/addr_o[2]} {u_bus2/u_master0/addr_o[3]} {u_bus2/u_master0/addr_o[4]} {u_bus2/u_master0/addr_o[5]} {u_bus2/u_master0/addr_o[6]} {u_bus2/u_master0/addr_o[7]} {u_bus2/u_master0/addr_o[8]} {u_bus2/u_master0/addr_o[9]} {u_bus2/u_master0/addr_o[10]} {u_bus2/u_master0/addr_o[11]} {u_bus2/u_master0/addr_o[12]} {u_bus2/u_master0/addr_o[13]} {u_bus2/u_master0/addr_o[14]} {u_bus2/u_master0/addr_o[15]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_bus2/u_master0/rdata_i[0]} {u_bus2/u_master0/rdata_i[1]} {u_bus2/u_master0/rdata_i[2]} {u_bus2/u_master0/rdata_i[3]} {u_bus2/u_master0/rdata_i[4]} {u_bus2/u_master0/rdata_i[5]} {u_bus2/u_master0/rdata_i[6]} {u_bus2/u_master0/rdata_i[7]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_bus2/u_slave0/addr_i[0]} {u_bus2/u_slave0/addr_i[1]} {u_bus2/u_slave0/addr_i[2]} {u_bus2/u_slave0/addr_i[3]} {u_bus2/u_slave0/addr_i[4]} {u_bus2/u_slave0/addr_i[5]} {u_bus2/u_slave0/addr_i[6]} {u_bus2/u_slave0/addr_i[7]} {u_bus2/u_slave0/addr_i[8]} {u_bus2/u_slave0/addr_i[9]} {u_bus2/u_slave0/addr_i[10]} {u_bus2/u_slave0/addr_i[11]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {u_bus1/u_master0/addr_o[0]} {u_bus1/u_master0/addr_o[1]} {u_bus1/u_master0/addr_o[2]} {u_bus1/u_master0/addr_o[3]} {u_bus1/u_master0/addr_o[4]} {u_bus1/u_master0/addr_o[5]} {u_bus1/u_master0/addr_o[6]} {u_bus1/u_master0/addr_o[7]} {u_bus1/u_master0/addr_o[8]} {u_bus1/u_master0/addr_o[9]} {u_bus1/u_master0/addr_o[10]} {u_bus1/u_master0/addr_o[11]} {u_bus1/u_master0/addr_o[12]} {u_bus1/u_master0/addr_o[13]} {u_bus1/u_master0/addr_o[14]} {u_bus1/u_master0/addr_o[15]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {u_bus1/u_slave0/addr_i[0]} {u_bus1/u_slave0/addr_i[1]} {u_bus1/u_slave0/addr_i[2]} {u_bus1/u_slave0/addr_i[3]} {u_bus1/u_slave0/addr_i[4]} {u_bus1/u_slave0/addr_i[5]} {u_bus1/u_slave0/addr_i[6]} {u_bus1/u_slave0/addr_i[7]} {u_bus1/u_slave0/addr_i[8]} {u_bus1/u_slave0/addr_i[9]} {u_bus1/u_slave0/addr_i[10]} {u_bus1/u_slave0/addr_i[11]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {u_bus1/u_master0/rdata_i[0]} {u_bus1/u_master0/rdata_i[1]} {u_bus1/u_master0/rdata_i[2]} {u_bus1/u_master0/rdata_i[3]} {u_bus1/u_master0/rdata_i[4]} {u_bus1/u_master0/rdata_i[5]} {u_bus1/u_master0/rdata_i[6]} {u_bus1/u_master0/rdata_i[7]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {u_bus1/u_master0/wdata_o[0]} {u_bus1/u_master0/wdata_o[1]} {u_bus1/u_master0/wdata_o[2]} {u_bus1/u_master0/wdata_o[3]} {u_bus1/u_master0/wdata_o[4]} {u_bus1/u_master0/wdata_o[5]} {u_bus1/u_master0/wdata_o[6]} {u_bus1/u_master0/wdata_o[7]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {u_bus1/u_slave0/wdata_i[0]} {u_bus1/u_slave0/wdata_i[1]} {u_bus1/u_slave0/wdata_i[2]} {u_bus1/u_slave0/wdata_i[3]} {u_bus1/u_slave0/wdata_i[4]} {u_bus1/u_slave0/wdata_i[5]} {u_bus1/u_slave0/wdata_i[6]} {u_bus1/u_slave0/wdata_i[7]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {u_bus1/u_slave0/rdata_o[0]} {u_bus1/u_slave0/rdata_o[1]} {u_bus1/u_slave0/rdata_o[2]} {u_bus1/u_slave0/rdata_o[3]} {u_bus1/u_slave0/rdata_o[4]} {u_bus1/u_slave0/rdata_o[5]} {u_bus1/u_slave0/rdata_o[6]} {u_bus1/u_slave0/rdata_o[7]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {u_bus1/u_slave2/rdata_o[0]} {u_bus1/u_slave2/rdata_o[1]} {u_bus1/u_slave2/rdata_o[2]} {u_bus1/u_slave2/rdata_o[3]} {u_bus1/u_slave2/rdata_o[4]} {u_bus1/u_slave2/rdata_o[5]} {u_bus1/u_slave2/rdata_o[6]} {u_bus1/u_slave2/rdata_o[7]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {u_bus1/u_slave2/wdata_i[0]} {u_bus1/u_slave2/wdata_i[1]} {u_bus1/u_slave2/wdata_i[2]} {u_bus1/u_slave2/wdata_i[3]} {u_bus1/u_slave2/wdata_i[4]} {u_bus1/u_slave2/wdata_i[5]} {u_bus1/u_slave2/wdata_i[6]} {u_bus1/u_slave2/wdata_i[7]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {u_bus1/u_slave1/addr_i[0]} {u_bus1/u_slave1/addr_i[1]} {u_bus1/u_slave1/addr_i[2]} {u_bus1/u_slave1/addr_i[3]} {u_bus1/u_slave1/addr_i[4]} {u_bus1/u_slave1/addr_i[5]} {u_bus1/u_slave1/addr_i[6]} {u_bus1/u_slave1/addr_i[7]} {u_bus1/u_slave1/addr_i[8]} {u_bus1/u_slave1/addr_i[9]} {u_bus1/u_slave1/addr_i[10]} {u_bus1/u_slave1/addr_i[11]}]]
connect_debug_port u_ila_0/probe16 [get_nets [list {u_bus1/u_slave1/wdata_i[0]} {u_bus1/u_slave1/wdata_i[1]} {u_bus1/u_slave1/wdata_i[2]} {u_bus1/u_slave1/wdata_i[3]} {u_bus1/u_slave1/wdata_i[4]} {u_bus1/u_slave1/wdata_i[5]} {u_bus1/u_slave1/wdata_i[6]} {u_bus1/u_slave1/wdata_i[7]}]]
connect_debug_port u_ila_0/probe17 [get_nets [list {u_bus1/u_slave2/addr_i[0]} {u_bus1/u_slave2/addr_i[1]} {u_bus1/u_slave2/addr_i[2]} {u_bus1/u_slave2/addr_i[3]} {u_bus1/u_slave2/addr_i[4]} {u_bus1/u_slave2/addr_i[5]} {u_bus1/u_slave2/addr_i[6]} {u_bus1/u_slave2/addr_i[7]} {u_bus1/u_slave2/addr_i[8]} {u_bus1/u_slave2/addr_i[9]} {u_bus1/u_slave2/addr_i[10]} {u_bus1/u_slave2/addr_i[11]}]]
connect_debug_port u_ila_0/probe18 [get_nets [list {u_bus1/u_slave1/rdata_o[0]} {u_bus1/u_slave1/rdata_o[1]} {u_bus1/u_slave1/rdata_o[2]} {u_bus1/u_slave1/rdata_o[3]} {u_bus1/u_slave1/rdata_o[4]} {u_bus1/u_slave1/rdata_o[5]} {u_bus1/u_slave1/rdata_o[6]} {u_bus1/u_slave1/rdata_o[7]}]]
connect_debug_port u_ila_0/probe19 [get_nets [list {u_bus2/u_slave0/rdata_o[0]} {u_bus2/u_slave0/rdata_o[1]} {u_bus2/u_slave0/rdata_o[2]} {u_bus2/u_slave0/rdata_o[3]} {u_bus2/u_slave0/rdata_o[4]} {u_bus2/u_slave0/rdata_o[5]} {u_bus2/u_slave0/rdata_o[6]} {u_bus2/u_slave0/rdata_o[7]}]]
connect_debug_port u_ila_0/probe20 [get_nets [list {u_bus2/u_slave0/wdata_i[0]} {u_bus2/u_slave0/wdata_i[1]} {u_bus2/u_slave0/wdata_i[2]} {u_bus2/u_slave0/wdata_i[3]} {u_bus2/u_slave0/wdata_i[4]} {u_bus2/u_slave0/wdata_i[5]} {u_bus2/u_slave0/wdata_i[6]} {u_bus2/u_slave0/wdata_i[7]}]]
connect_debug_port u_ila_0/probe21 [get_nets [list {u_bus2/u_slave2/rdata_o[0]} {u_bus2/u_slave2/rdata_o[1]} {u_bus2/u_slave2/rdata_o[2]} {u_bus2/u_slave2/rdata_o[3]} {u_bus2/u_slave2/rdata_o[4]} {u_bus2/u_slave2/rdata_o[5]} {u_bus2/u_slave2/rdata_o[6]} {u_bus2/u_slave2/rdata_o[7]}]]
connect_debug_port u_ila_0/probe22 [get_nets [list {u_bus2/u_slave2/wdata_i[0]} {u_bus2/u_slave2/wdata_i[1]} {u_bus2/u_slave2/wdata_i[2]} {u_bus2/u_slave2/wdata_i[3]} {u_bus2/u_slave2/wdata_i[4]} {u_bus2/u_slave2/wdata_i[5]} {u_bus2/u_slave2/wdata_i[6]} {u_bus2/u_slave2/wdata_i[7]}]]
connect_debug_port u_ila_0/probe23 [get_nets [list {u_bus2/u_slave2/addr_i[0]} {u_bus2/u_slave2/addr_i[1]} {u_bus2/u_slave2/addr_i[2]} {u_bus2/u_slave2/addr_i[3]} {u_bus2/u_slave2/addr_i[4]} {u_bus2/u_slave2/addr_i[5]} {u_bus2/u_slave2/addr_i[6]} {u_bus2/u_slave2/addr_i[7]} {u_bus2/u_slave2/addr_i[8]} {u_bus2/u_slave2/addr_i[9]} {u_bus2/u_slave2/addr_i[10]} {u_bus2/u_slave2/addr_i[11]}]]
connect_debug_port u_ila_0/probe24 [get_nets [list u_bus2/u_master0/ready_i]]
connect_debug_port u_ila_0/probe25 [get_nets [list u_bus1/u_master0/ready_i]]
connect_debug_port u_ila_0/probe26 [get_nets [list u_bus2/u_master0/valid_o]]
connect_debug_port u_ila_0/probe27 [get_nets [list u_bus1/u_master0/valid_o]]
set_property PACKAGE_PIN G15 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]



connect_debug_port u_ila_0/probe0 [get_nets [list {u_master0/addr_o[0]} {u_master0/addr_o[1]} {u_master0/addr_o[2]} {u_master0/addr_o[3]} {u_master0/addr_o[4]} {u_master0/addr_o[5]} {u_master0/addr_o[6]} {u_master0/addr_o[7]} {u_master0/addr_o[8]} {u_master0/addr_o[9]} {u_master0/addr_o[10]} {u_master0/addr_o[11]} {u_master0/addr_o[12]} {u_master0/addr_o[13]} {u_master0/addr_o[14]} {u_master0/addr_o[15]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_master0/wdata_o[0]} {u_master0/wdata_o[1]} {u_master0/wdata_o[2]} {u_master0/wdata_o[3]} {u_master0/wdata_o[4]} {u_master0/wdata_o[5]} {u_master0/wdata_o[6]} {u_master0/wdata_o[7]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_master1/rdata_i[0]} {u_master1/rdata_i[1]} {u_master1/rdata_i[2]} {u_master1/rdata_i[3]} {u_master1/rdata_i[4]} {u_master1/rdata_i[5]} {u_master1/rdata_i[6]} {u_master1/rdata_i[7]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_master1/addr_o[0]} {u_master1/addr_o[1]} {u_master1/addr_o[2]} {u_master1/addr_o[3]} {u_master1/addr_o[4]} {u_master1/addr_o[5]} {u_master1/addr_o[6]} {u_master1/addr_o[7]} {u_master1/addr_o[8]} {u_master1/addr_o[9]} {u_master1/addr_o[10]} {u_master1/addr_o[11]} {u_master1/addr_o[12]} {u_master1/addr_o[13]} {u_master1/addr_o[14]} {u_master1/addr_o[15]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_slave1/rdata_o[0]} {u_slave1/rdata_o[1]} {u_slave1/rdata_o[2]} {u_slave1/rdata_o[3]} {u_slave1/rdata_o[4]} {u_slave1/rdata_o[5]} {u_slave1/rdata_o[6]} {u_slave1/rdata_o[7]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_master1/wdata_o[0]} {u_master1/wdata_o[1]} {u_master1/wdata_o[2]} {u_master1/wdata_o[3]} {u_master1/wdata_o[4]} {u_master1/wdata_o[5]} {u_master1/wdata_o[6]} {u_master1/wdata_o[7]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_master0/rdata_i[0]} {u_master0/rdata_i[1]} {u_master0/rdata_i[2]} {u_master0/rdata_i[3]} {u_master0/rdata_i[4]} {u_master0/rdata_i[5]} {u_master0/rdata_i[6]} {u_master0/rdata_i[7]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {u_slave0/rdata_o[0]} {u_slave0/rdata_o[1]} {u_slave0/rdata_o[2]} {u_slave0/rdata_o[3]} {u_slave0/rdata_o[4]} {u_slave0/rdata_o[5]} {u_slave0/rdata_o[6]} {u_slave0/rdata_o[7]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {u_slave0/wdata_i[0]} {u_slave0/wdata_i[1]} {u_slave0/wdata_i[2]} {u_slave0/wdata_i[3]} {u_slave0/wdata_i[4]} {u_slave0/wdata_i[5]} {u_slave0/wdata_i[6]} {u_slave0/wdata_i[7]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {u_slave0/addr_i[0]} {u_slave0/addr_i[1]} {u_slave0/addr_i[2]} {u_slave0/addr_i[3]} {u_slave0/addr_i[4]} {u_slave0/addr_i[5]} {u_slave0/addr_i[6]} {u_slave0/addr_i[7]} {u_slave0/addr_i[8]} {u_slave0/addr_i[9]} {u_slave0/addr_i[10]} {u_slave0/addr_i[11]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {u_slave2/rdata_o[0]} {u_slave2/rdata_o[1]} {u_slave2/rdata_o[2]} {u_slave2/rdata_o[3]} {u_slave2/rdata_o[4]} {u_slave2/rdata_o[5]} {u_slave2/rdata_o[6]} {u_slave2/rdata_o[7]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list u_master0/ready_i]]
connect_debug_port u_ila_0/probe12 [get_nets [list u_master1/ready_i]]
connect_debug_port u_ila_0/probe13 [get_nets [list u_master0/valid_o]]
connect_debug_port u_ila_0/probe14 [get_nets [list u_master1/valid_o]]



connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]

connect_debug_port u_ila_0/clk [get_nets [list clk_a_IBUF_BUFG]]
connect_debug_port u_ila_0/probe1 [get_nets [list {b1s_addr[0]} {b1s_addr[1]} {b1s_addr[2]} {b1s_addr[3]} {b1s_addr[4]} {b1s_addr[5]} {b1s_addr[6]} {b1s_addr[7]} {b1s_addr[8]} {b1s_addr[9]} {b1s_addr[10]} {b1s_addr[11]} {b1s_addr[12]} {b1s_addr[13]} {b1s_addr[14]} {b1s_addr[15]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {b1s_wdata[0]} {b1s_wdata[1]} {b1s_wdata[2]} {b1s_wdata[3]} {b1s_wdata[4]} {b1s_wdata[5]} {b1s_wdata[6]} {b1s_wdata[7]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {b1s_rdata[0]} {b1s_rdata[1]} {b1s_rdata[2]} {b1s_rdata[3]} {b1s_rdata[4]} {b1s_rdata[5]} {b1s_rdata[6]} {b1s_rdata[7]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {b2s_addr[0]} {b2s_addr[1]} {b2s_addr[2]} {b2s_addr[3]} {b2s_addr[4]} {b2s_addr[5]} {b2s_addr[6]} {b2s_addr[7]} {b2s_addr[8]} {b2s_addr[9]} {b2s_addr[10]} {b2s_addr[11]} {b2s_addr[12]} {b2s_addr[13]} {b2s_addr[14]} {b2s_addr[15]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {b2s_rdata[0]} {b2s_rdata[1]} {b2s_rdata[2]} {b2s_rdata[3]} {b2s_rdata[4]} {b2s_rdata[5]} {b2s_rdata[6]} {b2s_rdata[7]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {b2s_wdata[0]} {b2s_wdata[1]} {b2s_wdata[2]} {b2s_wdata[3]} {b2s_wdata[4]} {b2s_wdata[5]} {b2s_wdata[6]} {b2s_wdata[7]}]]
connect_debug_port u_ila_0/probe28 [get_nets [list b1_arb_grant]]
connect_debug_port u_ila_0/probe29 [get_nets [list b1_arb_req]]
connect_debug_port u_ila_0/probe32 [get_nets [list b1m_rvalid]]
connect_debug_port u_ila_0/probe34 [get_nets [list b1s_grant]]
connect_debug_port u_ila_0/probe35 [get_nets [list b1s_ready]]
connect_debug_port u_ila_0/probe36 [get_nets [list b1s_req]]
connect_debug_port u_ila_0/probe37 [get_nets [list b1s_rvalid]]
connect_debug_port u_ila_0/probe38 [get_nets [list b1s_valid]]
connect_debug_port u_ila_0/probe42 [get_nets [list b2m_rvalid]]
connect_debug_port u_ila_0/probe44 [get_nets [list b2s_grant]]
connect_debug_port u_ila_0/probe45 [get_nets [list b2s_ready]]
connect_debug_port u_ila_0/probe46 [get_nets [list b2s_req]]
connect_debug_port u_ila_0/probe47 [get_nets [list b2s_rvalid]]
connect_debug_port u_ila_0/probe48 [get_nets [list b2s_valid]]
connect_debug_port dbg_hub/clk [get_nets clk_a_IBUF_BUFG]

connect_debug_port u_ila_0/probe0 [get_nets [list {u_bus2/u_slave2/rdata_o[0]} {u_bus2/u_slave2/rdata_o[1]} {u_bus2/u_slave2/rdata_o[2]} {u_bus2/u_slave2/rdata_o[3]} {u_bus2/u_slave2/rdata_o[4]} {u_bus2/u_slave2/rdata_o[5]} {u_bus2/u_slave2/rdata_o[6]} {u_bus2/u_slave2/rdata_o[7]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {b2m_addr[0]} {b2m_addr[1]} {b2m_addr[2]} {b2m_addr[3]} {b2m_addr[4]} {b2m_addr[5]} {b2m_addr[6]} {b2m_addr[7]} {b2m_addr[8]} {b2m_addr[9]} {b2m_addr[10]} {b2m_addr[11]} {b2m_addr[12]} {b2m_addr[13]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {b1m_addr[0]} {b1m_addr[1]} {b1m_addr[2]} {b1m_addr[3]} {b1m_addr[4]} {b1m_addr[5]} {b1m_addr[6]} {b1m_addr[7]} {b1m_addr[8]} {b1m_addr[9]} {b1m_addr[10]} {b1m_addr[11]} {b1m_addr[12]} {b1m_addr[13]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {b1m_wdata[0]} {b1m_wdata[1]} {b1m_wdata[2]} {b1m_wdata[3]} {b1m_wdata[4]} {b1m_wdata[5]} {b1m_wdata[6]} {b1m_wdata[7]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {b2m_rdata[0]} {b2m_rdata[1]} {b2m_rdata[2]} {b2m_rdata[3]} {b2m_rdata[4]} {b2m_rdata[5]} {b2m_rdata[6]} {b2m_rdata[7]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {b2m_wdata[0]} {b2m_wdata[1]} {b2m_wdata[2]} {b2m_wdata[3]} {b2m_wdata[4]} {b2m_wdata[5]} {b2m_wdata[6]} {b2m_wdata[7]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {b1m_rdata[0]} {b1m_rdata[1]} {b1m_rdata[2]} {b1m_rdata[3]} {b1m_rdata[4]} {b1m_rdata[5]} {b1m_rdata[6]} {b1m_rdata[7]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {u_bus1/u_master0/rdata_i[0]} {u_bus1/u_master0/rdata_i[1]} {u_bus1/u_master0/rdata_i[2]} {u_bus1/u_master0/rdata_i[3]} {u_bus1/u_master0/rdata_i[4]} {u_bus1/u_master0/rdata_i[5]} {u_bus1/u_master0/rdata_i[6]} {u_bus1/u_master0/rdata_i[7]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {u_bus1/u_master0/addr_o[0]} {u_bus1/u_master0/addr_o[1]} {u_bus1/u_master0/addr_o[2]} {u_bus1/u_master0/addr_o[3]} {u_bus1/u_master0/addr_o[4]} {u_bus1/u_master0/addr_o[5]} {u_bus1/u_master0/addr_o[6]} {u_bus1/u_master0/addr_o[7]} {u_bus1/u_master0/addr_o[8]} {u_bus1/u_master0/addr_o[9]} {u_bus1/u_master0/addr_o[10]} {u_bus1/u_master0/addr_o[11]} {u_bus1/u_master0/addr_o[12]} {u_bus1/u_master0/addr_o[13]} {u_bus1/u_master0/addr_o[14]} {u_bus1/u_master0/addr_o[15]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {u_bus1/u_master0/wdata_o[0]} {u_bus1/u_master0/wdata_o[1]} {u_bus1/u_master0/wdata_o[2]} {u_bus1/u_master0/wdata_o[3]} {u_bus1/u_master0/wdata_o[4]} {u_bus1/u_master0/wdata_o[5]} {u_bus1/u_master0/wdata_o[6]} {u_bus1/u_master0/wdata_o[7]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {u_bus1/u_slave0/addr_i[0]} {u_bus1/u_slave0/addr_i[1]} {u_bus1/u_slave0/addr_i[2]} {u_bus1/u_slave0/addr_i[3]} {u_bus1/u_slave0/addr_i[4]} {u_bus1/u_slave0/addr_i[5]} {u_bus1/u_slave0/addr_i[6]} {u_bus1/u_slave0/addr_i[7]} {u_bus1/u_slave0/addr_i[8]} {u_bus1/u_slave0/addr_i[9]} {u_bus1/u_slave0/addr_i[10]} {u_bus1/u_slave0/addr_i[11]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {u_bus1/u_slave1/rdata_o[0]} {u_bus1/u_slave1/rdata_o[1]} {u_bus1/u_slave1/rdata_o[2]} {u_bus1/u_slave1/rdata_o[3]} {u_bus1/u_slave1/rdata_o[4]} {u_bus1/u_slave1/rdata_o[5]} {u_bus1/u_slave1/rdata_o[6]} {u_bus1/u_slave1/rdata_o[7]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {u_bus1/u_slave0/rdata_o[0]} {u_bus1/u_slave0/rdata_o[1]} {u_bus1/u_slave0/rdata_o[2]} {u_bus1/u_slave0/rdata_o[3]} {u_bus1/u_slave0/rdata_o[4]} {u_bus1/u_slave0/rdata_o[5]} {u_bus1/u_slave0/rdata_o[6]} {u_bus1/u_slave0/rdata_o[7]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {u_bus1/u_slave0/wdata_i[0]} {u_bus1/u_slave0/wdata_i[1]} {u_bus1/u_slave0/wdata_i[2]} {u_bus1/u_slave0/wdata_i[3]} {u_bus1/u_slave0/wdata_i[4]} {u_bus1/u_slave0/wdata_i[5]} {u_bus1/u_slave0/wdata_i[6]} {u_bus1/u_slave0/wdata_i[7]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {u_bus1/u_slave2/rdata_o[0]} {u_bus1/u_slave2/rdata_o[1]} {u_bus1/u_slave2/rdata_o[2]} {u_bus1/u_slave2/rdata_o[3]} {u_bus1/u_slave2/rdata_o[4]} {u_bus1/u_slave2/rdata_o[5]} {u_bus1/u_slave2/rdata_o[6]} {u_bus1/u_slave2/rdata_o[7]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {u_bus2/u_master0/addr_o[0]} {u_bus2/u_master0/addr_o[1]} {u_bus2/u_master0/addr_o[2]} {u_bus2/u_master0/addr_o[3]} {u_bus2/u_master0/addr_o[4]} {u_bus2/u_master0/addr_o[5]} {u_bus2/u_master0/addr_o[6]} {u_bus2/u_master0/addr_o[7]} {u_bus2/u_master0/addr_o[8]} {u_bus2/u_master0/addr_o[9]} {u_bus2/u_master0/addr_o[10]} {u_bus2/u_master0/addr_o[11]} {u_bus2/u_master0/addr_o[12]} {u_bus2/u_master0/addr_o[13]} {u_bus2/u_master0/addr_o[14]} {u_bus2/u_master0/addr_o[15]}]]
connect_debug_port u_ila_0/probe16 [get_nets [list {u_bus2/u_master0/rdata_i[0]} {u_bus2/u_master0/rdata_i[1]} {u_bus2/u_master0/rdata_i[2]} {u_bus2/u_master0/rdata_i[3]} {u_bus2/u_master0/rdata_i[4]} {u_bus2/u_master0/rdata_i[5]} {u_bus2/u_master0/rdata_i[6]} {u_bus2/u_master0/rdata_i[7]}]]
connect_debug_port u_ila_0/probe17 [get_nets [list {u_bus2/u_master0/wdata_o[0]} {u_bus2/u_master0/wdata_o[1]} {u_bus2/u_master0/wdata_o[2]} {u_bus2/u_master0/wdata_o[3]} {u_bus2/u_master0/wdata_o[4]} {u_bus2/u_master0/wdata_o[5]} {u_bus2/u_master0/wdata_o[6]} {u_bus2/u_master0/wdata_o[7]}]]
connect_debug_port u_ila_0/probe18 [get_nets [list {u_bus2/u_slave0/rdata_o[0]} {u_bus2/u_slave0/rdata_o[1]} {u_bus2/u_slave0/rdata_o[2]} {u_bus2/u_slave0/rdata_o[3]} {u_bus2/u_slave0/rdata_o[4]} {u_bus2/u_slave0/rdata_o[5]} {u_bus2/u_slave0/rdata_o[6]} {u_bus2/u_slave0/rdata_o[7]}]]
connect_debug_port u_ila_0/probe19 [get_nets [list {u_bus2/u_slave1/rdata_o[0]} {u_bus2/u_slave1/rdata_o[1]} {u_bus2/u_slave1/rdata_o[2]} {u_bus2/u_slave1/rdata_o[3]} {u_bus2/u_slave1/rdata_o[4]} {u_bus2/u_slave1/rdata_o[5]} {u_bus2/u_slave1/rdata_o[6]} {u_bus2/u_slave1/rdata_o[7]}]]
connect_debug_port u_ila_0/probe20 [get_nets [list {u_bus2/u_slave0/addr_i[0]} {u_bus2/u_slave0/addr_i[1]} {u_bus2/u_slave0/addr_i[2]} {u_bus2/u_slave0/addr_i[3]} {u_bus2/u_slave0/addr_i[4]} {u_bus2/u_slave0/addr_i[5]} {u_bus2/u_slave0/addr_i[6]} {u_bus2/u_slave0/addr_i[7]} {u_bus2/u_slave0/addr_i[8]} {u_bus2/u_slave0/addr_i[9]} {u_bus2/u_slave0/addr_i[10]} {u_bus2/u_slave0/addr_i[11]}]]
connect_debug_port u_ila_0/probe21 [get_nets [list {u_bus2/u_slave0/wdata_i[0]} {u_bus2/u_slave0/wdata_i[1]} {u_bus2/u_slave0/wdata_i[2]} {u_bus2/u_slave0/wdata_i[3]} {u_bus2/u_slave0/wdata_i[4]} {u_bus2/u_slave0/wdata_i[5]} {u_bus2/u_slave0/wdata_i[6]} {u_bus2/u_slave0/wdata_i[7]}]]
connect_debug_port u_ila_0/probe22 [get_nets [list b1m_grant]]
connect_debug_port u_ila_0/probe23 [get_nets [list b1m_ready]]
connect_debug_port u_ila_0/probe24 [get_nets [list b1m_req]]
connect_debug_port u_ila_0/probe25 [get_nets [list b1m_valid]]
connect_debug_port u_ila_0/probe26 [get_nets [list b2m_grant]]
connect_debug_port u_ila_0/probe27 [get_nets [list b2m_ready]]
connect_debug_port u_ila_0/probe28 [get_nets [list b2m_req]]
connect_debug_port u_ila_0/probe29 [get_nets [list b2m_valid]]
connect_debug_port u_ila_0/probe30 [get_nets [list u_bus1/u_master0/ready_i]]
connect_debug_port u_ila_0/probe31 [get_nets [list u_bus2/u_master0/ready_i]]
connect_debug_port u_ila_0/probe32 [get_nets [list u_bus1/u_master0/valid_o]]
connect_debug_port u_ila_0/probe33 [get_nets [list u_bus2/u_master0/valid_o]]

connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_master0/addr_o[0]} {u_master0/addr_o[1]} {u_master0/addr_o[2]} {u_master0/addr_o[3]} {u_master0/addr_o[4]} {u_master0/addr_o[5]} {u_master0/addr_o[6]} {u_master0/addr_o[7]} {u_master0/addr_o[8]} {u_master0/addr_o[9]} {u_master0/addr_o[10]} {u_master0/addr_o[11]} {u_master0/addr_o[12]} {u_master0/addr_o[13]} {u_master0/addr_o[14]} {u_master0/addr_o[15]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_master0/rdata_i[0]} {u_master0/rdata_i[1]} {u_master0/rdata_i[2]} {u_master0/rdata_i[3]} {u_master0/rdata_i[4]} {u_master0/rdata_i[5]} {u_master0/rdata_i[6]} {u_master0/rdata_i[7]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_master0/wdata_o[0]} {u_master0/wdata_o[1]} {u_master0/wdata_o[2]} {u_master0/wdata_o[3]} {u_master0/wdata_o[4]} {u_master0/wdata_o[5]} {u_master0/wdata_o[6]} {u_master0/wdata_o[7]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {rdata_s[0]} {rdata_s[1]} {rdata_s[2]} {rdata_s[3]} {rdata_s[4]} {rdata_s[5]} {rdata_s[6]} {rdata_s[7]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_slave_bridge/state[0]} {u_slave_bridge/state[1]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {addr_ext_o[0]} {addr_ext_o[1]} {addr_ext_o[2]} {addr_ext_o[3]} {addr_ext_o[4]} {addr_ext_o[5]} {addr_ext_o[6]} {addr_ext_o[7]} {addr_ext_o[8]} {addr_ext_o[9]} {addr_ext_o[10]} {addr_ext_o[11]} {addr_ext_o[12]} {addr_ext_o[13]} {addr_ext_o[14]} {addr_ext_o[15]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {addr_s[0]} {addr_s[1]} {addr_s[2]} {addr_s[3]} {addr_s[4]} {addr_s[5]} {addr_s[6]} {addr_s[7]} {addr_s[8]} {addr_s[9]} {addr_s[10]} {addr_s[11]} {addr_s[12]} {addr_s[13]} {addr_s[14]} {addr_s[15]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {idx[0]} {idx[1]} {idx[2]} {idx[3]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {rdata_ext_i[0]} {rdata_ext_i[1]} {rdata_ext_i[2]} {rdata_ext_i[3]} {rdata_ext_i[4]} {rdata_ext_i[5]} {rdata_ext_i[6]} {rdata_ext_i[7]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {wdata_s[0]} {wdata_s[1]} {wdata_s[2]} {wdata_s[3]} {wdata_s[4]} {wdata_s[5]} {wdata_s[6]} {wdata_s[7]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {wdata_ext_o[0]} {wdata_ext_o[1]} {wdata_ext_o[2]} {wdata_ext_o[3]} {wdata_ext_o[4]} {wdata_ext_o[5]} {wdata_ext_o[6]} {wdata_ext_o[7]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list u_slave_bridge/addr_got]]
connect_debug_port u_ila_0/probe12 [get_nets [list u_slave_bridge/addr_rx_ready]]
connect_debug_port u_ila_0/probe13 [get_nets [list ext_valid_o]]
connect_debug_port u_ila_0/probe14 [get_nets [list grant_ext]]
connect_debug_port u_ila_0/probe15 [get_nets [list u_master_bridge/grant_pulse]]
connect_debug_port u_ila_0/probe16 [get_nets [list grant_s]]
connect_debug_port u_ila_0/probe17 [get_nets [list link_grant_tx]]
connect_debug_port u_ila_0/probe18 [get_nets [list link_req_tx]]
connect_debug_port u_ila_0/probe19 [get_nets [list u_master_bridge/m_state]]
connect_debug_port u_ila_0/probe20 [get_nets [list ready_ext_i]]
connect_debug_port u_ila_0/probe21 [get_nets [list u_master0/ready_i]]
connect_debug_port u_ila_0/probe22 [get_nets [list ready_s]]
connect_debug_port u_ila_0/probe23 [get_nets [list req_ext]]
connect_debug_port u_ila_0/probe24 [get_nets [list u_slave_bridge/req_pulse]]
connect_debug_port u_ila_0/probe25 [get_nets [list req_s]]
connect_debug_port u_ila_0/probe26 [get_nets [list u_master_bridge/req_tx_o_dbg]]
connect_debug_port u_ila_0/probe27 [get_nets [list rvalid_ext_i]]
connect_debug_port u_ila_0/probe28 [get_nets [list rvalid_s]]
connect_debug_port u_ila_0/probe29 [get_nets [list start_en]]
connect_debug_port u_ila_0/probe30 [get_nets [list u_master_bridge/tx_data_en]]
connect_debug_port u_ila_0/probe31 [get_nets [list u_master0/valid_o]]
connect_debug_port u_ila_0/probe32 [get_nets [list valid_s]]
connect_debug_port u_ila_0/probe33 [get_nets [list u_slave_bridge/wdata_got]]
connect_debug_port u_ila_0/probe34 [get_nets [list u_slave_bridge/wdata_rx_ready]]
connect_debug_port u_ila_0/probe35 [get_nets [list we_s]]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]

connect_debug_port u_ila_0/clk [get_nets [list clk_a_IBUF_BUFG]]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_bus1/u_master0/addr_o[0]} {u_bus1/u_master0/addr_o[1]} {u_bus1/u_master0/addr_o[2]} {u_bus1/u_master0/addr_o[3]} {u_bus1/u_master0/addr_o[4]} {u_bus1/u_master0/addr_o[5]} {u_bus1/u_master0/addr_o[6]} {u_bus1/u_master0/addr_o[7]} {u_bus1/u_master0/addr_o[8]} {u_bus1/u_master0/addr_o[9]} {u_bus1/u_master0/addr_o[10]} {u_bus1/u_master0/addr_o[11]} {u_bus1/u_master0/addr_o[12]} {u_bus1/u_master0/addr_o[13]} {u_bus1/u_master0/addr_o[14]} {u_bus1/u_master0/addr_o[15]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_slave_bridge_b1/state[0]} {u_slave_bridge_b1/state[1]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_slave_bridge_b2/state[0]} {u_slave_bridge_b2/state[1]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_bus1/u_master0/rdata_i[0]} {u_bus1/u_master0/rdata_i[1]} {u_bus1/u_master0/rdata_i[2]} {u_bus1/u_master0/rdata_i[3]} {u_bus1/u_master0/rdata_i[4]} {u_bus1/u_master0/rdata_i[5]} {u_bus1/u_master0/rdata_i[6]} {u_bus1/u_master0/rdata_i[7]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_bus1/u_master0/wdata_o[0]} {u_bus1/u_master0/wdata_o[1]} {u_bus1/u_master0/wdata_o[2]} {u_bus1/u_master0/wdata_o[3]} {u_bus1/u_master0/wdata_o[4]} {u_bus1/u_master0/wdata_o[5]} {u_bus1/u_master0/wdata_o[6]} {u_bus1/u_master0/wdata_o[7]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_bus1/u_slave0/rdata_o[0]} {u_bus1/u_slave0/rdata_o[1]} {u_bus1/u_slave0/rdata_o[2]} {u_bus1/u_slave0/rdata_o[3]} {u_bus1/u_slave0/rdata_o[4]} {u_bus1/u_slave0/rdata_o[5]} {u_bus1/u_slave0/rdata_o[6]} {u_bus1/u_slave0/rdata_o[7]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_bus1/u_slave0/addr_i[0]} {u_bus1/u_slave0/addr_i[1]} {u_bus1/u_slave0/addr_i[2]} {u_bus1/u_slave0/addr_i[3]} {u_bus1/u_slave0/addr_i[4]} {u_bus1/u_slave0/addr_i[5]} {u_bus1/u_slave0/addr_i[6]} {u_bus1/u_slave0/addr_i[7]} {u_bus1/u_slave0/addr_i[8]} {u_bus1/u_slave0/addr_i[9]} {u_bus1/u_slave0/addr_i[10]} {u_bus1/u_slave0/addr_i[11]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {u_bus1/u_slave0/wdata_i[0]} {u_bus1/u_slave0/wdata_i[1]} {u_bus1/u_slave0/wdata_i[2]} {u_bus1/u_slave0/wdata_i[3]} {u_bus1/u_slave0/wdata_i[4]} {u_bus1/u_slave0/wdata_i[5]} {u_bus1/u_slave0/wdata_i[6]} {u_bus1/u_slave0/wdata_i[7]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {u_bus1/u_slave2/rdata_o[0]} {u_bus1/u_slave2/rdata_o[1]} {u_bus1/u_slave2/rdata_o[2]} {u_bus1/u_slave2/rdata_o[3]} {u_bus1/u_slave2/rdata_o[4]} {u_bus1/u_slave2/rdata_o[5]} {u_bus1/u_slave2/rdata_o[6]} {u_bus1/u_slave2/rdata_o[7]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {u_bus1/u_slave1/rdata_o[0]} {u_bus1/u_slave1/rdata_o[1]} {u_bus1/u_slave1/rdata_o[2]} {u_bus1/u_slave1/rdata_o[3]} {u_bus1/u_slave1/rdata_o[4]} {u_bus1/u_slave1/rdata_o[5]} {u_bus1/u_slave1/rdata_o[6]} {u_bus1/u_slave1/rdata_o[7]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {u_bus2/u_master0/rdata_i[0]} {u_bus2/u_master0/rdata_i[1]} {u_bus2/u_master0/rdata_i[2]} {u_bus2/u_master0/rdata_i[3]} {u_bus2/u_master0/rdata_i[4]} {u_bus2/u_master0/rdata_i[5]} {u_bus2/u_master0/rdata_i[6]} {u_bus2/u_master0/rdata_i[7]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {u_bus2/u_master0/addr_o[0]} {u_bus2/u_master0/addr_o[1]} {u_bus2/u_master0/addr_o[2]} {u_bus2/u_master0/addr_o[3]} {u_bus2/u_master0/addr_o[4]} {u_bus2/u_master0/addr_o[5]} {u_bus2/u_master0/addr_o[6]} {u_bus2/u_master0/addr_o[7]} {u_bus2/u_master0/addr_o[8]} {u_bus2/u_master0/addr_o[9]} {u_bus2/u_master0/addr_o[10]} {u_bus2/u_master0/addr_o[11]} {u_bus2/u_master0/addr_o[12]} {u_bus2/u_master0/addr_o[13]} {u_bus2/u_master0/addr_o[14]} {u_bus2/u_master0/addr_o[15]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {u_bus2/u_master0/wdata_o[0]} {u_bus2/u_master0/wdata_o[1]} {u_bus2/u_master0/wdata_o[2]} {u_bus2/u_master0/wdata_o[3]} {u_bus2/u_master0/wdata_o[4]} {u_bus2/u_master0/wdata_o[5]} {u_bus2/u_master0/wdata_o[6]} {u_bus2/u_master0/wdata_o[7]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {u_bus2/u_slave0/addr_i[0]} {u_bus2/u_slave0/addr_i[1]} {u_bus2/u_slave0/addr_i[2]} {u_bus2/u_slave0/addr_i[3]} {u_bus2/u_slave0/addr_i[4]} {u_bus2/u_slave0/addr_i[5]} {u_bus2/u_slave0/addr_i[6]} {u_bus2/u_slave0/addr_i[7]} {u_bus2/u_slave0/addr_i[8]} {u_bus2/u_slave0/addr_i[9]} {u_bus2/u_slave0/addr_i[10]} {u_bus2/u_slave0/addr_i[11]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {u_bus2/u_slave1/rdata_o[0]} {u_bus2/u_slave1/rdata_o[1]} {u_bus2/u_slave1/rdata_o[2]} {u_bus2/u_slave1/rdata_o[3]} {u_bus2/u_slave1/rdata_o[4]} {u_bus2/u_slave1/rdata_o[5]} {u_bus2/u_slave1/rdata_o[6]} {u_bus2/u_slave1/rdata_o[7]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {u_bus2/u_slave0/rdata_o[0]} {u_bus2/u_slave0/rdata_o[1]} {u_bus2/u_slave0/rdata_o[2]} {u_bus2/u_slave0/rdata_o[3]} {u_bus2/u_slave0/rdata_o[4]} {u_bus2/u_slave0/rdata_o[5]} {u_bus2/u_slave0/rdata_o[6]} {u_bus2/u_slave0/rdata_o[7]}]]
connect_debug_port u_ila_0/probe16 [get_nets [list {u_bus2/u_slave0/wdata_i[0]} {u_bus2/u_slave0/wdata_i[1]} {u_bus2/u_slave0/wdata_i[2]} {u_bus2/u_slave0/wdata_i[3]} {u_bus2/u_slave0/wdata_i[4]} {u_bus2/u_slave0/wdata_i[5]} {u_bus2/u_slave0/wdata_i[6]} {u_bus2/u_slave0/wdata_i[7]}]]
connect_debug_port u_ila_0/probe17 [get_nets [list {u_bus2/u_slave2/rdata_o[0]} {u_bus2/u_slave2/rdata_o[1]} {u_bus2/u_slave2/rdata_o[2]} {u_bus2/u_slave2/rdata_o[3]} {u_bus2/u_slave2/rdata_o[4]} {u_bus2/u_slave2/rdata_o[5]} {u_bus2/u_slave2/rdata_o[6]} {u_bus2/u_slave2/rdata_o[7]}]]
connect_debug_port u_ila_0/probe18 [get_nets [list {b2m_rdata[0]} {b2m_rdata[1]} {b2m_rdata[2]} {b2m_rdata[3]} {b2m_rdata[4]} {b2m_rdata[5]} {b2m_rdata[6]} {b2m_rdata[7]}]]
connect_debug_port u_ila_0/probe19 [get_nets [list {b1m_addr[0]} {b1m_addr[1]} {b1m_addr[2]} {b1m_addr[3]} {b1m_addr[4]} {b1m_addr[5]} {b1m_addr[6]} {b1m_addr[7]} {b1m_addr[8]} {b1m_addr[9]} {b1m_addr[10]} {b1m_addr[11]} {b1m_addr[12]} {b1m_addr[13]}]]
connect_debug_port u_ila_0/probe20 [get_nets [list {b1m_wdata[0]} {b1m_wdata[1]} {b1m_wdata[2]} {b1m_wdata[3]} {b1m_wdata[4]} {b1m_wdata[5]} {b1m_wdata[6]} {b1m_wdata[7]}]]
connect_debug_port u_ila_0/probe21 [get_nets [list {b1s_wdata[0]} {b1s_wdata[1]} {b1s_wdata[2]} {b1s_wdata[3]} {b1s_wdata[4]} {b1s_wdata[5]} {b1s_wdata[6]} {b1s_wdata[7]}]]
connect_debug_port u_ila_0/probe22 [get_nets [list {b2s_wdata[0]} {b2s_wdata[1]} {b2s_wdata[2]} {b2s_wdata[3]} {b2s_wdata[4]} {b2s_wdata[5]} {b2s_wdata[6]} {b2s_wdata[7]}]]
connect_debug_port u_ila_0/probe23 [get_nets [list {b1s_addr[0]} {b1s_addr[1]} {b1s_addr[2]} {b1s_addr[3]} {b1s_addr[4]} {b1s_addr[5]} {b1s_addr[6]} {b1s_addr[7]} {b1s_addr[8]} {b1s_addr[9]} {b1s_addr[10]} {b1s_addr[11]} {b1s_addr[12]} {b1s_addr[13]} {b1s_addr[14]} {b1s_addr[15]}]]
connect_debug_port u_ila_0/probe24 [get_nets [list {b1s_rdata[0]} {b1s_rdata[1]} {b1s_rdata[2]} {b1s_rdata[3]} {b1s_rdata[4]} {b1s_rdata[5]} {b1s_rdata[6]} {b1s_rdata[7]}]]
connect_debug_port u_ila_0/probe25 [get_nets [list {b2s_rdata[0]} {b2s_rdata[1]} {b2s_rdata[2]} {b2s_rdata[3]} {b2s_rdata[4]} {b2s_rdata[5]} {b2s_rdata[6]} {b2s_rdata[7]}]]
connect_debug_port u_ila_0/probe26 [get_nets [list {b2s_addr[0]} {b2s_addr[1]} {b2s_addr[2]} {b2s_addr[3]} {b2s_addr[4]} {b2s_addr[5]} {b2s_addr[6]} {b2s_addr[7]} {b2s_addr[8]} {b2s_addr[9]} {b2s_addr[10]} {b2s_addr[11]} {b2s_addr[12]} {b2s_addr[13]} {b2s_addr[14]} {b2s_addr[15]}]]
connect_debug_port u_ila_0/probe27 [get_nets [list {b1m_rdata[0]} {b1m_rdata[1]} {b1m_rdata[2]} {b1m_rdata[3]} {b1m_rdata[4]} {b1m_rdata[5]} {b1m_rdata[6]} {b1m_rdata[7]}]]
connect_debug_port u_ila_0/probe28 [get_nets [list {b2m_wdata[0]} {b2m_wdata[1]} {b2m_wdata[2]} {b2m_wdata[3]} {b2m_wdata[4]} {b2m_wdata[5]} {b2m_wdata[6]} {b2m_wdata[7]}]]
connect_debug_port u_ila_0/probe29 [get_nets [list {b2m_addr[0]} {b2m_addr[1]} {b2m_addr[2]} {b2m_addr[3]} {b2m_addr[4]} {b2m_addr[5]} {b2m_addr[6]} {b2m_addr[7]} {b2m_addr[8]} {b2m_addr[9]} {b2m_addr[10]} {b2m_addr[11]} {b2m_addr[12]} {b2m_addr[13]}]]
connect_debug_port u_ila_0/probe30 [get_nets [list u_slave_bridge_b1/addr_got]]
connect_debug_port u_ila_0/probe31 [get_nets [list u_slave_bridge_b2/addr_got]]
connect_debug_port u_ila_0/probe32 [get_nets [list u_slave_bridge_b1/addr_rx_ready]]
connect_debug_port u_ila_0/probe33 [get_nets [list u_slave_bridge_b2/addr_rx_ready]]
connect_debug_port u_ila_0/probe34 [get_nets [list b1_arb_grant]]
connect_debug_port u_ila_0/probe35 [get_nets [list b1_arb_req]]
connect_debug_port u_ila_0/probe36 [get_nets [list b1m_grant]]
connect_debug_port u_ila_0/probe37 [get_nets [list b1m_ready]]
connect_debug_port u_ila_0/probe38 [get_nets [list b1m_rvalid]]
connect_debug_port u_ila_0/probe39 [get_nets [list b1m_valid]]
connect_debug_port u_ila_0/probe40 [get_nets [list b1s_grant]]
connect_debug_port u_ila_0/probe41 [get_nets [list b1s_ready]]
connect_debug_port u_ila_0/probe42 [get_nets [list b1s_req]]
connect_debug_port u_ila_0/probe43 [get_nets [list b1s_rvalid]]
connect_debug_port u_ila_0/probe44 [get_nets [list b1s_valid]]
connect_debug_port u_ila_0/probe45 [get_nets [list b2m_grant]]
connect_debug_port u_ila_0/probe46 [get_nets [list b2m_ready]]
connect_debug_port u_ila_0/probe47 [get_nets [list b2m_req]]
connect_debug_port u_ila_0/probe48 [get_nets [list b2m_rvalid]]
connect_debug_port u_ila_0/probe49 [get_nets [list b2m_valid]]
connect_debug_port u_ila_0/probe50 [get_nets [list b2s_grant]]
connect_debug_port u_ila_0/probe51 [get_nets [list b2s_ready]]
connect_debug_port u_ila_0/probe52 [get_nets [list b2s_req]]
connect_debug_port u_ila_0/probe53 [get_nets [list b2s_rvalid]]
connect_debug_port u_ila_0/probe54 [get_nets [list b2s_valid]]
connect_debug_port u_ila_0/probe55 [get_nets [list u_master_bridge_b1/grant_pulse]]
connect_debug_port u_ila_0/probe56 [get_nets [list u_master_bridge_b2/grant_pulse]]
connect_debug_port u_ila_0/probe57 [get_nets [list u_master_bridge_b1/m_state]]
connect_debug_port u_ila_0/probe58 [get_nets [list u_master_bridge_b2/m_state]]
connect_debug_port u_ila_0/probe59 [get_nets [list u_bus1/u_master0/ready_i]]
connect_debug_port u_ila_0/probe60 [get_nets [list u_bus2/u_master0/ready_i]]
connect_debug_port u_ila_0/probe61 [get_nets [list u_slave_bridge_b1/req_pulse]]
connect_debug_port u_ila_0/probe62 [get_nets [list u_slave_bridge_b2/req_pulse]]
connect_debug_port u_ila_0/probe63 [get_nets [list u_master_bridge_b1/req_tx_o_dbg]]
connect_debug_port u_ila_0/probe64 [get_nets [list u_master_bridge_b2/req_tx_o_dbg]]
connect_debug_port u_ila_0/probe65 [get_nets [list u_master_bridge_b1/tx_data_en]]
connect_debug_port u_ila_0/probe66 [get_nets [list u_master_bridge_b2/tx_data_en]]
connect_debug_port u_ila_0/probe67 [get_nets [list u_bus1/u_master0/valid_o]]
connect_debug_port u_ila_0/probe68 [get_nets [list u_bus2/u_master0/valid_o]]
connect_debug_port u_ila_0/probe69 [get_nets [list u_slave_bridge_b1/wdata_got]]
connect_debug_port u_ila_0/probe70 [get_nets [list u_slave_bridge_b2/wdata_got]]
connect_debug_port u_ila_0/probe71 [get_nets [list u_slave_bridge_b1/wdata_rx_ready]]
connect_debug_port u_ila_0/probe72 [get_nets [list u_slave_bridge_b2/wdata_rx_ready]]
connect_debug_port dbg_hub/clk [get_nets clk_a_IBUF_BUFG]

set_property PACKAGE_PIN R14 [get_ports tx_req_o]
set_property PACKAGE_PIN P14 [get_ports rx_grant_i]
set_property PACKAGE_PIN T15 [get_ports tx_addr_o]
set_property PACKAGE_PIN V18 [get_ports tx_wdata_o]
set_property PACKAGE_PIN V17 [get_ports rx_status_i]
set_property PACKAGE_PIN U15 [get_ports rx_ready_i]
set_property PACKAGE_PIN T10 [get_ports rx_req_i]
set_property PACKAGE_PIN T11 [get_ports tx_grant_o]
set_property PACKAGE_PIN W15 [get_ports rx_addr_i]
set_property PACKAGE_PIN U12 [get_ports rx_wdata_i]
set_property PACKAGE_PIN T12 [get_ports tx_status_o]
set_property PACKAGE_PIN Y14 [get_ports tx_ready_o]
set_property IOSTANDARD LVCMOS33 [get_ports rx_addr_i]
set_property IOSTANDARD LVCMOS33 [get_ports tx_grant_o]
set_property IOSTANDARD LVCMOS33 [get_ports rx_wdata_i]
set_property IOSTANDARD LVCMOS33 [get_ports rx_status_i]
set_property IOSTANDARD LVCMOS33 [get_ports tx_addr_o]
set_property IOSTANDARD LVCMOS33 [get_ports tx_ready_o]
set_property IOSTANDARD LVCMOS33 [get_ports tx_req_o]
set_property IOSTANDARD LVCMOS33 [get_ports tx_status_o]
set_property IOSTANDARD LVCMOS33 [get_ports tx_wdata_o]
set_property IOSTANDARD LVCMOS33 [get_ports rx_req_i]
set_property IOSTANDARD LVCMOS33 [get_ports rx_grant_i]
set_property IOSTANDARD LVCMOS33 [get_ports rx_ready_i]
set_property DRIVE 12 [get_ports tx_addr_o]
set_property SLEW SLOW [get_ports tx_addr_o]

connect_debug_port u_ila_0/probe0 [get_nets [list {u_bus/u_master0/wdata_o[0]} {u_bus/u_master0/wdata_o[1]} {u_bus/u_master0/wdata_o[2]} {u_bus/u_master0/wdata_o[3]} {u_bus/u_master0/wdata_o[4]} {u_bus/u_master0/wdata_o[5]} {u_bus/u_master0/wdata_o[6]} {u_bus/u_master0/wdata_o[7]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_bus/u_master0/addr_o[0]} {u_bus/u_master0/addr_o[1]} {u_bus/u_master0/addr_o[2]} {u_bus/u_master0/addr_o[3]} {u_bus/u_master0/addr_o[4]} {u_bus/u_master0/addr_o[5]} {u_bus/u_master0/addr_o[6]} {u_bus/u_master0/addr_o[7]} {u_bus/u_master0/addr_o[8]} {u_bus/u_master0/addr_o[9]} {u_bus/u_master0/addr_o[10]} {u_bus/u_master0/addr_o[11]} {u_bus/u_master0/addr_o[12]} {u_bus/u_master0/addr_o[13]} {u_bus/u_master0/addr_o[14]} {u_bus/u_master0/addr_o[15]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_bus/u_master0/rdata_i[0]} {u_bus/u_master0/rdata_i[1]} {u_bus/u_master0/rdata_i[2]} {u_bus/u_master0/rdata_i[3]} {u_bus/u_master0/rdata_i[4]} {u_bus/u_master0/rdata_i[5]} {u_bus/u_master0/rdata_i[6]} {u_bus/u_master0/rdata_i[7]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_bus/u_slave0/rdata_o[0]} {u_bus/u_slave0/rdata_o[1]} {u_bus/u_slave0/rdata_o[2]} {u_bus/u_slave0/rdata_o[3]} {u_bus/u_slave0/rdata_o[4]} {u_bus/u_slave0/rdata_o[5]} {u_bus/u_slave0/rdata_o[6]} {u_bus/u_slave0/rdata_o[7]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_bus/u_slave1/addr_i[0]} {u_bus/u_slave1/addr_i[1]} {u_bus/u_slave1/addr_i[2]} {u_bus/u_slave1/addr_i[3]} {u_bus/u_slave1/addr_i[4]} {u_bus/u_slave1/addr_i[5]} {u_bus/u_slave1/addr_i[6]} {u_bus/u_slave1/addr_i[7]} {u_bus/u_slave1/addr_i[8]} {u_bus/u_slave1/addr_i[9]} {u_bus/u_slave1/addr_i[10]} {u_bus/u_slave1/addr_i[11]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_bus/u_slave1/wdata_i[0]} {u_bus/u_slave1/wdata_i[1]} {u_bus/u_slave1/wdata_i[2]} {u_bus/u_slave1/wdata_i[3]} {u_bus/u_slave1/wdata_i[4]} {u_bus/u_slave1/wdata_i[5]} {u_bus/u_slave1/wdata_i[6]} {u_bus/u_slave1/wdata_i[7]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {u_bus/u_slave0/wdata_i[0]} {u_bus/u_slave0/wdata_i[1]} {u_bus/u_slave0/wdata_i[2]} {u_bus/u_slave0/wdata_i[3]} {u_bus/u_slave0/wdata_i[4]} {u_bus/u_slave0/wdata_i[5]} {u_bus/u_slave0/wdata_i[6]} {u_bus/u_slave0/wdata_i[7]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {u_bus/u_slave0/addr_i[0]} {u_bus/u_slave0/addr_i[1]} {u_bus/u_slave0/addr_i[2]} {u_bus/u_slave0/addr_i[3]} {u_bus/u_slave0/addr_i[4]} {u_bus/u_slave0/addr_i[5]} {u_bus/u_slave0/addr_i[6]} {u_bus/u_slave0/addr_i[7]} {u_bus/u_slave0/addr_i[8]} {u_bus/u_slave0/addr_i[9]} {u_bus/u_slave0/addr_i[10]} {u_bus/u_slave0/addr_i[11]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {u_bus/u_slave1/rdata_o[0]} {u_bus/u_slave1/rdata_o[1]} {u_bus/u_slave1/rdata_o[2]} {u_bus/u_slave1/rdata_o[3]} {u_bus/u_slave1/rdata_o[4]} {u_bus/u_slave1/rdata_o[5]} {u_bus/u_slave1/rdata_o[6]} {u_bus/u_slave1/rdata_o[7]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {u_bus/u_slave2/wdata_i[0]} {u_bus/u_slave2/wdata_i[1]} {u_bus/u_slave2/wdata_i[2]} {u_bus/u_slave2/wdata_i[3]} {u_bus/u_slave2/wdata_i[4]} {u_bus/u_slave2/wdata_i[5]} {u_bus/u_slave2/wdata_i[6]} {u_bus/u_slave2/wdata_i[7]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {u_bus/u_slave2/addr_i[0]} {u_bus/u_slave2/addr_i[1]} {u_bus/u_slave2/addr_i[2]} {u_bus/u_slave2/addr_i[3]} {u_bus/u_slave2/addr_i[4]} {u_bus/u_slave2/addr_i[5]} {u_bus/u_slave2/addr_i[6]} {u_bus/u_slave2/addr_i[7]} {u_bus/u_slave2/addr_i[8]} {u_bus/u_slave2/addr_i[9]} {u_bus/u_slave2/addr_i[10]} {u_bus/u_slave2/addr_i[11]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {u_bus/u_slave2/rdata_o[0]} {u_bus/u_slave2/rdata_o[1]} {u_bus/u_slave2/rdata_o[2]} {u_bus/u_slave2/rdata_o[3]} {u_bus/u_slave2/rdata_o[4]} {u_bus/u_slave2/rdata_o[5]} {u_bus/u_slave2/rdata_o[6]} {u_bus/u_slave2/rdata_o[7]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {m1_addr[0]} {m1_addr[1]} {m1_addr[2]} {m1_addr[3]} {m1_addr[4]} {m1_addr[5]} {m1_addr[6]} {m1_addr[7]} {m1_addr[8]} {m1_addr[9]} {m1_addr[10]} {m1_addr[11]} {m1_addr[12]} {m1_addr[13]} {m1_addr[14]} {m1_addr[15]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {m1_rdata[0]} {m1_rdata[1]} {m1_rdata[2]} {m1_rdata[3]} {m1_rdata[4]} {m1_rdata[5]} {m1_rdata[6]} {m1_rdata[7]}]]
connect_debug_port u_ila_0/probe17 [get_nets [list {m1_wdata[0]} {m1_wdata[1]} {m1_wdata[2]} {m1_wdata[3]} {m1_wdata[4]} {m1_wdata[5]} {m1_wdata[6]} {m1_wdata[7]}]]
connect_debug_port u_ila_0/probe27 [get_nets [list m1_grant]]
connect_debug_port u_ila_0/probe28 [get_nets [list m1_ready]]
connect_debug_port u_ila_0/probe29 [get_nets [list m1_req]]
connect_debug_port u_ila_0/probe30 [get_nets [list m1_rvalid]]
connect_debug_port u_ila_0/probe31 [get_nets [list m1_valid]]
connect_debug_port u_ila_0/probe33 [get_nets [list u_bus/u_master0/ready_i]]
connect_debug_port u_ila_0/probe37 [get_nets [list u_bus/u_master0/valid_o]]
set_property PACKAGE_PIN M14 [get_ports {led[3]}]
set_property PACKAGE_PIN M15 [get_ports {led[2]}]
set_property PACKAGE_PIN G14 [get_ports {led[1]}]
set_property PACKAGE_PIN D18 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]

set_property PACKAGE_PIN W20 [get_ports uart_rx_serial]
set_property PACKAGE_PIN V20 [get_ports uart_tx_serial]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_serial]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_serial]

